# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import wallet_pb2 as wallet__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """1. Client <-> Node (Functional Requirements)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/wallet.WalletService/CreateAccount',
                request_serializer=wallet__pb2.AccountRequest.SerializeToString,
                response_deserializer=wallet__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/wallet.WalletService/GetBalance',
                request_serializer=wallet__pb2.AccountRequest.SerializeToString,
                response_deserializer=wallet__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.ExecuteTransaction = channel.unary_unary(
                '/wallet.WalletService/ExecuteTransaction',
                request_serializer=wallet__pb2.TransactionRequest.SerializeToString,
                response_deserializer=wallet__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.TransferFunds = channel.unary_unary(
                '/wallet.WalletService/TransferFunds',
                request_serializer=wallet__pb2.TransactionRequest.SerializeToString,
                response_deserializer=wallet__pb2.TransactionResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """1. Client <-> Node (Functional Requirements)
    """

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTransaction(self, request, context):
        """Updated: Supports Deposit/Withdraw
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferFunds(self, request, context):
        """Kept for future use (Cross-Shard)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=wallet__pb2.AccountRequest.FromString,
                    response_serializer=wallet__pb2.AccountResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=wallet__pb2.AccountRequest.FromString,
                    response_serializer=wallet__pb2.BalanceResponse.SerializeToString,
            ),
            'ExecuteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTransaction,
                    request_deserializer=wallet__pb2.TransactionRequest.FromString,
                    response_serializer=wallet__pb2.TransactionResponse.SerializeToString,
            ),
            'TransferFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFunds,
                    request_deserializer=wallet__pb2.TransactionRequest.FromString,
                    response_serializer=wallet__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """1. Client <-> Node (Functional Requirements)
    """

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/CreateAccount',
            wallet__pb2.AccountRequest.SerializeToString,
            wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetBalance',
            wallet__pb2.AccountRequest.SerializeToString,
            wallet__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/ExecuteTransaction',
            wallet__pb2.TransactionRequest.SerializeToString,
            wallet__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/TransferFunds',
            wallet__pb2.TransactionRequest.SerializeToString,
            wallet__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConsensusServiceStub(object):
    """2. Node <-> Node (Raft Consensus for High Availability)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/wallet.ConsensusService/RequestVote',
                request_serializer=wallet__pb2.VoteRequest.SerializeToString,
                response_deserializer=wallet__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/wallet.ConsensusService/AppendEntries',
                request_serializer=wallet__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=wallet__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)


class ConsensusServiceServicer(object):
    """2. Node <-> Node (Raft Consensus for High Availability)
    """

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=wallet__pb2.VoteRequest.FromString,
                    response_serializer=wallet__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=wallet__pb2.AppendEntriesRequest.FromString,
                    response_serializer=wallet__pb2.AppendEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.ConsensusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """2. Node <-> Node (Raft Consensus for High Availability)
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.ConsensusService/RequestVote',
            wallet__pb2.VoteRequest.SerializeToString,
            wallet__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.ConsensusService/AppendEntries',
            wallet__pb2.AppendEntriesRequest.SerializeToString,
            wallet__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ShardServiceStub(object):
    """3. Shard <-> Shard (2PC for Atomicity)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/wallet.ShardService/Prepare',
                request_serializer=wallet__pb2.TwoPCRequest.SerializeToString,
                response_deserializer=wallet__pb2.TwoPCResponse.FromString,
                _registered_method=True)
        self.CommitOrAbort = channel.unary_unary(
                '/wallet.ShardService/CommitOrAbort',
                request_serializer=wallet__pb2.TwoPCRequest.SerializeToString,
                response_deserializer=wallet__pb2.TwoPCResponse.FromString,
                _registered_method=True)


class ShardServiceServicer(object):
    """3. Shard <-> Shard (2PC for Atomicity)
    """

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitOrAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=wallet__pb2.TwoPCRequest.FromString,
                    response_serializer=wallet__pb2.TwoPCResponse.SerializeToString,
            ),
            'CommitOrAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOrAbort,
                    request_deserializer=wallet__pb2.TwoPCRequest.FromString,
                    response_serializer=wallet__pb2.TwoPCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.ShardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.ShardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardService(object):
    """3. Shard <-> Shard (2PC for Atomicity)
    """

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.ShardService/Prepare',
            wallet__pb2.TwoPCRequest.SerializeToString,
            wallet__pb2.TwoPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitOrAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.ShardService/CommitOrAbort',
            wallet__pb2.TwoPCRequest.SerializeToString,
            wallet__pb2.TwoPCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
